### ISSUE TITLE
Accept non-USA time zones and post codes

### ISSUE THREAD

**Issue by z3ugma** [codykociemba/NoLongerEvil-Thermostat#76]
Request:  Recognise Europe exists and return correct European PostCodes in  data rather than some random US one. My Nest thinks it lives near Chicago USA, rather than Brighton UK, and is reset to US Central time,  each time  NLE  data  is returned to the Nest!    But you already know this.  😉   Just for the record. 

Another person in the UK reports their Nest defaults to Cheney Wa .

**Comment by z3ugma** [comment]
"Hi Guys, I'm in the UK and have a schedule set Monday to Friday for heating at 6am
The other day the heating came on at 00.40.
I check the settings and it had set it's location to Cheney KS or something like that.
I set it back to UK and entered my postcode and it worked the next day fine .
Then last night my heating came on again at 00.40.
I have just checked and it had reset it's location back to Cheney KS again ?

"

**Comment by z3ugma** [comment]
"I bought a second-hand version 2 Nest to experiment with.  It appeared to be working well after flashing. The only thing I noticed was setting the time showed US Time Zones - I am in the UK. So I set it to a UK time and left it on Central as I had no way of setting a zone for my location.  This morning the heating was off.  It seems the clock has set itself to US Central Time.  Is this a rogue eBay purchase with a US  Nest origin or is this a software issue?    My nest thinks it's 4:52 AM whilst I'm living in 10:52.   I suppose I could reset the schedule  by 6 hours....  But I've replaced my original unaltered Nest back."

**Comment by z3ugma** [comment]
Related to #52 ?

**Comment by hnewman** [comment]
I'm in Canada and also getting reset my location reset to Cheney, KS

**Comment by z3ugma** [comment]
@hnewman are you comfortable sharing the postcode that you're using? Or you can DM in Discord

**Comment by hnewman** [comment]
> [@hnewman](https://github.com/hnewman) are you comfortable sharing the postcode that you're using? Or you can DM in Discord

H2S 3K3.  I corrected it last night and it's already flipped back to Cheney, KS.  I'd swap my snow for 76 degrees and sunny gladly

**Comment by codykociemba** [comment]
This should be fixed in the latest update, give it a try and let me know. Thanks!

**Comment by FirefoxSystem** [comment]
The same thing happens to me.
It's not possible to update the location from the dashboard: "Filed to update location" red message.
I set the zip code directly from the thermostat a few hours ago and it's still correct.
I'm in Italy.

**EDIT:** This morning the location setup magically appeared

**Comment by ddsdude** [comment]
Not fixed for me. I am in Canada, input everything and get a failed to save error.

**Comment by codykociemba** [comment]
Give it another try, new update has been pushed.

**Comment by ddsdude** [comment]
Fixed! Works great now including outdoor temperature display. Thank you!

EDIT: Spoke too soon. When I try to add my time zone and street address, it errors with "failed to insert structure state" and does not save the data.

**Comment by FirefoxSystem** [comment]
As I wrote above, the position has been showing since this morning, but if I try to change it, I get the message in red:

![Image](https://github.com/user-attachments/assets/bce8680b-d5bd-4475-9ed8-c5f83c331c47)

**Comment by codykociemba** [comment]
Can you try restarting the Nest?

**Comment by FirefoxSystem** [comment]
> Can you try restarting the Nest?

Yes, I restarted Nest and tried logging out of the dashboard, but nothing changed when I logged back in.

**Comment by codykociemba** [comment]
You’ll likely need to delete the thermostat from your NLE account and re-pair it with a new entry code. For some reason, the structure state which binds it to your account was malformed or deleted.

**Comment by FirefoxSystem** [comment]
> You’ll likely need to delete the thermostat from your NLE account and re-pair it with a new entry code. For some reason, the structure state which binds it to your account was malformed or deleted.

I tried as you suggested, removed Nest but now I can't add it anymore :(

![Image](https://github.com/user-attachments/assets/30d2b884-e3e8-4590-9dfc-3b680109f0c7)

If I remember correctly, the first time I didn't type the hyphen "-" now I have to add it manually but it doesn't work

**Comment by codykociemba** [comment]
The hyphen isn’t required to be typed. It’s failing because the Nest is caching your account and automatically re-adding it. If you go back to your dashboard, it likely is now back in there even though it said it failed. Try to restart the Nest device and while it reboots, immediately delete it from your NLE account. If you do these two actions at the same time, it should force a reset of the cached account and allow you to re-claim it again via a new entry code.

I’ll add a fix for this soon once I find out how to force remove the cached account from the Nest, but in the meantime this should solve it as a quick fix.

**Comment by hnewman** [comment]
> This should be fixed in the latest update, give it a try and let me know. Thanks!

Still acting weird, and now won't let me use Celsius (I could before)

<img width="1080" height="2424" alt="Image" src="https://github.com/user-attachments/assets/5ea81da5-3e5e-4e2f-befd-513564be9581" />

**Comment by FirefoxSystem** [comment]
> The hyphen isn’t required to be typed. It’s failing because the Nest is caching your account and automatically re-adding it. If you go back to your dashboard, it likely is now back in there even though it said it failed. Try to restart the Nest device and while it reboots, immediately delete it from your NLE account. If you do these two actions at the same time, it should force a reset of the cached account and allow you to re-claim it again via a new entry code.
> 
> I’ll add a fix for this soon once I find out how to force remove the cached account from the Nest, but in the meantime this should solve it as a quick fix.

Nothing works, I can't add my Nest anymore. I've tried 5 or 6 times with different entry keys over a few hours, and I always get the same error message: "Failed to claim entry key." I also tried creating a second account and adding it to this one, but the problem still occurs.

I tried pinging Nest from PowerShell, but it's not responding. I don't know if this is normal.
Do I need to flash the device a second time?
Is that possible?

**Comment by hnewman** [comment]
> > This should be fixed in the latest update, give it a try and let me know. Thanks!
> 
> Still acting weird, and now won't let me use Celsius (I could before)
> 

Not sure if you pushed changes, but all seems to be working properly now

**Comment by milkywaymusicianharp** [comment]
@FirefoxSystem You're not alone, I also can't change my country to the UK or time zone to GMT.

"Failed to insert structure state"

It's weird, because I was getting that when trying to switch to Celcius but that seems to have sorted itself out and displays in C now.

I don't want to start the process of unlinking and relinking my NLE Themostat just yet until I know that really is the fix. I love this project!

**Comment by FirefoxSystem** [comment]
> [@FirefoxSystem](https://github.com/FirefoxSystem) You're not alone, I also can't change my country to the UK or time zone to GMT.
> 
> "Failed to insert structure state"
> 
> It's weird, because I was getting that when trying to switch to Celcius but that seems to have sorted itself out and displays in C now.
> 
> I don't want to start the process of unlinking and relinking my NLE Themostat just yet until I know that really is the fix. I love this project!

I bought a Chinese thermostat for €35.00 (AVATTO WT20R BH). Until there's anything new, I'll use this one. Then, if it works, I'll just throw my Nest in the trash!

**Comment by milkywaymusicianharp** [comment]
That's an interesting looking device, some reviews on AliExpress about the sensor being off . Please recycle responsibly or sell your old Nest!  This project is going to bring new life to them once it's working.

**Comment by FirefoxSystem** [comment]
Of course, I won't throw it in the trash—that was just a figure of speech, driven by anger towards Google. However, since my device no longer works with NLE after dozens of attempts, I fear I'll have to throw it in the same box as many dead devices. Rationally, I can't wait months or years for a remotely controllable thermostat, and I think it will be a long time before a mobile app exists.

**Comment by ChrisCalavera** [comment]
I'm also getting the "Failed to insert structure state" message when trying to change the location. I have 3 thermostats - do I need to remove and add all 3 again?

Edit: I can set the location on the thermostats directly and that seems to stick and update on the NLE website

**Comment by FirefoxSystem** [comment]
Update

After procuring a temporary Chinese thermostat (to allow the heating to function normally without leaving the family in the cold), I factory reset my Nest, flashed it again, and was finally able to reintegrate the thermostat into the NLE website.
Via the browser, everything seems to work correctly, including geographic location and the Celsius temperature scale.
The thermostat now seems to be detecting a higher room temperature than it was previously. That is, right now, the house is 19.6°C, and on the NLE page, the reading is 21.8°C, a 2.2-degree difference. I don't know if this is due to the flash or an accuracy error in my reference thermometer, which is actually the one built into my Amazon Echo Dot; I don't know how accurate it is.

I'm using the Nest European version with a HeatLink unit, and unlike the previous situation—when the thermostat was installed in the home system—this time on the workbench, I was able to pair the thermostat to the HeatLink unit wirelessly as well as wired. Much to my surprise, after rebooting, a firmware update occurred. Where do you think this update came from? From Google? 

My Home Assistant instance runs on a Docker server in a Synology NAS, and I installed Mosquitto broker from SynoCommunity on it.
I then configured the mosquitto.conf file via SSH (and I'm not sure if I did everything correctly) but I also got stuck configuring MQTT on Home Assistant.

I'm sorry, but I'm a Home Assistant beginner.
Could someone please tell me where I can find a beginner's guide on how to configure MQTT?
Thank you very much.

**Comment by mvasilakis** [comment]
> I'm sorry, but I'm a Home Assistant beginner. Could someone please tell me where I can find a beginner's guide on how to configure MQTT? Thank you very much.

There is a HACS integration for Home Assistant so you don't need to set it up with MQTT directly:
https://github.com/patricktr/NoLongerEvil-HomeAssistant

**Comment by FirefoxSystem** [comment]
> There is a HACS integration for Home Assistant so you don't need to set it up with MQTT directly:

Sorry, I obviously didn't dig deep enough! :)

Great, it works perfectly.
You really did a great job!
Congratulations, thank you very much.
